/**
 * Pilot paths listed in the downloadable import sample report (unset checklist).
 * Shared with `scripts/report-sample-import-gaps.mjs`.
 */

/** @type {string[]} */
export const PILOT_IMPORT_REPORT_TRACK_PATHS = [
  'mission.fileId',
  'mission.title',
  'mission.alternateTitle',
  'mission.abstract',
  'mission.purpose',
  'mission.startDate',
  'mission.endDate',
  'mission.publicationDate',
  'mission.metadataRecordDate',
  'mission.language',
  'mission.status',
  'mission.doi',
  'mission.accession',
  'mission.org',
  'mission.individualName',
  'mission.email',
  'mission.contactUrl',
  'mission.topicCategories',
  'mission.graphicOverviewHref',
  'mission.parentProjectTitle',
  'mission.relatedDataUrl',
  'mission.relatedDatasetTitle',
  'mission.citationAuthorOrganisationName',
  'spatial.referenceSystem',
  'spatial.geographicDescription',
  'spatial.lineageStatement',
  'spatial.accuracyValue',
  'spatial.verticalCrsUrl',
  'platform.platformId',
  'platform.platformDesc',
  'platform.manufacturer',
  'distribution.landingUrl',
  'distribution.downloadUrl',
  'distribution.metadataLandingUrl',
  'distribution.format',
  'keywords.sciencekeywords',
  'keywords.datacenters',
  'keywords.platforms',
  'keywords.instruments',
  'keywords.locations',
  'keywords.projects',
  'keywords.providers',
]
