/**
 * SWARM lane reporter — consolidates batch audit reports into one
 * PASS / CHECK / BLOCK dashboard.
 *
 * Reads existing report JSON files from reports/ subdirs and emits:
 *   reports/batch-report.json   machine-readable lane summary
 *   reports/batch-report.md     human-readable dashboard
 *
 * Usage:
 *   node scripts/batch/batch-report.mjs
 *   node scripts/batch/batch-report.mjs --reports-dir reports --out reports/batch-report.json
 *   node scripts/batch/batch-report.mjs --xml-dir fixtures/mission   (runs inline audit first)
 *
 * @module scripts/batch/batch-report
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  ensureXmldomPolyfill,
  loadXmlDir,
  extractUuid,
  extractUrls,
  extractImageUrls,
  isDocucompUrl,
  isNoddUrl,
  isOsddUrl,
  writeJson,
} from './_xml.mjs'

ensureXmldomPolyfill()

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REACT_PILOT = path.resolve(__dirname, '../..')

function parseArgs(argv) {
  const out = {
    reportsDir: path.join(REACT_PILOT, 'reports'),
    outJson: path.join(REACT_PILOT, 'reports/batch-report.json'),
    outMd: path.join(REACT_PILOT, 'reports/batch-report.md'),
    xmlDir: '',
  }
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i]
    if (a === '--reports-dir') out.reportsDir = path.resolve(REACT_PILOT, argv[++i] || '')
    else if (a === '--out') out.outJson = path.resolve(REACT_PILOT, argv[++i] || '')
    else if (a === '--xml-dir') out.xmlDir = path.resolve(REACT_PILOT, argv[++i] || '')
  }
  return out
}

function loadJsonIfExists(p) {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')) } catch { return null }
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

function inlineLaneFromXmlDir(xmlDir) {
  const records = loadXmlDir(xmlDir)
  if (records.length === 0) return null

  let validUuids = 0, missingUuids = 0, dupUuids = 0
  let totalUrls = 0, brokenPlaceholder = 0
  let noddCount = 0, osddCount = 0, docucompCount = 0
  let totalImages = 0, docucompImages = 0
  const uuidSeen = new Map()

  for (const rec of records) {
    const uuid = extractUuid(rec.doc)
    if (!uuid) {
      missingUuids += 1
    } else if (!UUID_RE.test(uuid)) {
      missingUuids += 1
    } else {
      if (!uuidSeen.has(uuid)) uuidSeen.set(uuid, 0)
      uuidSeen.set(uuid, uuidSeen.get(uuid) + 1)
      validUuids += 1
    }

    const urls = extractUrls(rec.doc)
    totalUrls += urls.length
    noddCount += urls.filter(isNoddUrl).length
    osddCount += urls.filter(isOsddUrl).length
    docucompCount += urls.filter(isDocucompUrl).length

    const images = extractImageUrls(rec.doc)
    totalImages += images.length
    docucompImages += images.filter((i) => isDocucompUrl(i.url)).length
  }

  for (const [, count] of uuidSeen) {
    if (count > 1) dupUuids += 1
  }

  const uuidIssues = missingUuids + dupUuids
  const noddPresent = noddCount > 0
  const osddPresent = osddCount > 0

  return {
    totalXmlRecords: records.length,
    uuids: { valid: validUuids, missing: missingUuids, duplicates: dupUuids },
    urls: { total: totalUrls, nodd: noddCount, osdd: osddCount, docucomp: docucompCount },
    images: { total: totalImages, docucomp: docucompImages },
    lanes: {
      uuidIntegrity: uuidIssues === 0 ? 'PASS' : uuidIssues <= 3 ? 'CHECK' : 'BLOCK',
      noddCloudLinks: noddPresent ? 'PASS' : 'CHECK',
      osddLinks: osddPresent ? 'PASS' : 'CHECK',
      docucompIntegrity: docucompCount > 0 ? 'PASS' : 'CHECK',
      imageUrlIntegrity: totalImages > 0 ? 'PASS' : 'CHECK',
    },
  }
}

function statusIcon(s) {
  if (s === 'PASS') return '✓ PASS'
  if (s === 'CHECK') return '~ CHECK'
  if (s === 'BLOCK') return '✗ BLOCK'
  return '? UNKNOWN'
}

function buildMarkdown(report) {
  const lines = [
    '# Manta Batch Audit — Lane Report',
    '',
    `Generated: ${report.generated}`,
    '',
    '## Lane Summary',
    '',
    '| Lane | Status | Detail |',
    '|------|--------|--------|',
  ]

  for (const lane of report.lanes) {
    lines.push(`| ${lane.name} | ${statusIcon(lane.status)} | ${lane.detail} |`)
  }

  lines.push('', '## Counts', '')
  if (report.totals) {
    for (const [k, v] of Object.entries(report.totals)) {
      lines.push(`- **${k}**: ${v}`)
    }
  }

  lines.push('', '---', '_Generated by Manta Batch Engine_')
  return lines.join('\n')
}

async function main() {
  const opts = parseArgs(process.argv.slice(2))

  let inline = null
  if (opts.xmlDir && fs.existsSync(opts.xmlDir)) {
    console.log(`Running inline XML analysis on: ${opts.xmlDir}`)
    inline = inlineLaneFromXmlDir(opts.xmlDir)
  } else {
    // try fixtures as fallback
    const fixtureDir = path.join(REACT_PILOT, 'fixtures/mission')
    if (fs.existsSync(fixtureDir)) {
      console.log(`Analyzing fixtures: ${fixtureDir}`)
      inline = inlineLaneFromXmlDir(fixtureDir)
    }
  }

  // read existing sub-reports
  const wafSummary = loadJsonIfExists(path.join(opts.reportsDir, 'waf-audit/summary.json'))
  const uuidSummary = loadJsonIfExists(path.join(opts.reportsDir, 'uuid-audit/uuid-audit.json'))
  const noddSummary = loadJsonIfExists(path.join(opts.reportsDir, 'nodd-plan/nodd-plan.json'))
  const osddSummary = loadJsonIfExists(path.join(opts.reportsDir, 'osdd-plan/osdd-plan.json'))

  // build lanes array
  const lanes = []

  // XML certification lane — from inline or fixture analysis
  if (inline) {
    lanes.push({
      name: 'xmlCertification',
      status: 'PASS',
      detail: `${inline.totalXmlRecords} records analysed via inline engine`,
    })
    lanes.push({
      name: 'uuidIntegrity',
      status: inline.lanes.uuidIntegrity,
      detail: `valid=${inline.uuids.valid} missing=${inline.uuids.missing} dupes=${inline.uuids.duplicates}`,
    })
    lanes.push({
      name: 'noddCloudLinks',
      status: inline.lanes.noddCloudLinks,
      detail: `${inline.urls.nodd} NODD URLs found across ${inline.totalXmlRecords} records`,
    })
    lanes.push({
      name: 'osddLinks',
      status: inline.lanes.osddLinks,
      detail: `${inline.urls.osdd} OSDD URLs found across ${inline.totalXmlRecords} records`,
    })
    lanes.push({
      name: 'docucompIntegrity',
      status: inline.lanes.docucompIntegrity,
      detail: `${inline.urls.docucomp} DocuComp URLs, ${inline.images.docucomp}/${inline.images.total} DocuComp images`,
    })
    lanes.push({
      name: 'imageUrlIntegrity',
      status: inline.lanes.imageUrlIntegrity,
      detail: `${inline.images.total} browse graphic URLs found`,
    })
  } else {
    lanes.push({ name: 'xmlCertification', status: 'CHECK', detail: 'No XML dir provided — run with --xml-dir' })
    lanes.push({ name: 'uuidIntegrity', status: 'CHECK', detail: 'No XML dir provided' })
    lanes.push({ name: 'noddCloudLinks', status: 'CHECK', detail: 'No XML dir provided' })
    lanes.push({ name: 'osddLinks', status: 'CHECK', detail: 'No XML dir provided' })
    lanes.push({ name: 'docucompIntegrity', status: 'CHECK', detail: 'No XML dir provided' })
    lanes.push({ name: 'imageUrlIntegrity', status: 'CHECK', detail: 'No XML dir provided' })
  }

  // WAF link health lane
  if (wafSummary) {
    lanes.push({
      name: 'wafLinkHealth',
      status: wafSummary.laneStatus || 'CHECK',
      detail: `${wafSummary.totalUniqueUrls} URLs checked, ${wafSummary.brokenUrls} broken`,
    })
  } else {
    lanes.push({ name: 'wafLinkHealth', status: 'CHECK', detail: 'Run: npm run batch:waf:audit -- --xml-dir <path>' })
  }

  // NODD plan lane
  if (noddSummary) {
    lanes.push({
      name: 'noddPlan',
      status: noddSummary.laneStatus || 'CHECK',
      detail: `${noddSummary.applied || noddSummary.planned || 0} records, ${noddSummary.notFound} not found`,
    })
  } else {
    lanes.push({ name: 'noddPlan', status: 'CHECK', detail: 'Run: npm run batch:nodd:plan -- --csv nodd.csv --xml-dir <path>' })
  }

  // OSDD plan lane
  if (osddSummary) {
    lanes.push({
      name: 'osddPlan',
      status: osddSummary.laneStatus || 'CHECK',
      detail: `${osddSummary.applied || osddSummary.planned || 0} records, ${osddSummary.notFound} not found`,
    })
  } else {
    lanes.push({ name: 'osddPlan', status: 'CHECK', detail: 'Run: npm run batch:osdd:plan -- --csv osdd.csv --xml-dir <path>' })
  }

  // UUID audit lane (from uuid-audit sub-report)
  if (uuidSummary) {
    lanes.push({
      name: 'uuidAudit',
      status: uuidSummary.laneStatus || 'CHECK',
      detail: `valid=${uuidSummary.uuids?.valid} missing=${uuidSummary.uuids?.missing} dupes=${uuidSummary.uuids?.duplicates}`,
    })
  }

  // overall
  const hasBlock = lanes.some((l) => l.status === 'BLOCK')
  const hasCheck = lanes.some((l) => l.status === 'CHECK')
  const overallStatus = hasBlock ? 'BLOCK' : hasCheck ? 'CHECK' : 'PASS'

  const passCount = lanes.filter((l) => l.status === 'PASS').length
  const checkCount = lanes.filter((l) => l.status === 'CHECK').length
  const blockCount = lanes.filter((l) => l.status === 'BLOCK').length

  const totals = inline
    ? {
        xmlRecords: inline.totalXmlRecords,
        totalUrls: inline.urls.total,
        noddUrls: inline.urls.nodd,
        osddUrls: inline.urls.osdd,
        docucompUrls: inline.urls.docucomp,
        imageUrls: inline.images.total,
        docucompImages: inline.images.docucomp,
      }
    : {}

  const report = {
    generated: new Date().toISOString(),
    overallStatus,
    summary: { pass: passCount, check: checkCount, block: blockCount },
    lanes,
    totals,
  }

  fs.mkdirSync(path.dirname(opts.outJson), { recursive: true })
  writeJson(opts.outJson, report)
  fs.writeFileSync(opts.outMd, buildMarkdown(report), 'utf8')

  console.log('\n══ MANTA BATCH LANE REPORT ══════════════════════════════════')
  for (const lane of lanes) {
    const icon = lane.status === 'PASS' ? '✓' : lane.status === 'BLOCK' ? '✗' : '~'
    console.log(`  ${icon} ${lane.name.padEnd(22)} ${lane.status.padEnd(8)}  ${lane.detail}`)
  }
  console.log('─────────────────────────────────────────────────────────────')
  console.log(`  OVERALL: ${overallStatus}   (${passCount} PASS / ${checkCount} CHECK / ${blockCount} BLOCK)`)
  console.log('─────────────────────────────────────────────────────────────')
  console.log(`\nReports: ${opts.outJson}`)
  console.log(`         ${opts.outMd}`)

  if (overallStatus === 'BLOCK') process.exit(1)
}

main().catch((e) => { console.error(e); process.exit(1) })
